# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appWindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameMainButtons = QtWidgets.QFrame(self.centralwidget)
        self.frameMainButtons.setGeometry(QtCore.QRect(-1, 0, 901, 51))
        self.frameMainButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMainButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMainButtons.setObjectName("frameMainButtons")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frameMainButtons)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 901, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButtonHome = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButtonHome.setAutoRepeat(False)
        self.toolButtonHome.setAutoExclusive(True)
        self.toolButtonHome.setAutoRaise(False)
        self.toolButtonHome.setObjectName("toolButtonHome")
        self.horizontalLayout.addWidget(self.toolButtonHome)
        self.toolButtonCP = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButtonCP.setAutoExclusive(True)
        self.toolButtonCP.setObjectName("toolButtonCP")
        self.horizontalLayout.addWidget(self.toolButtonCP)
        self.toolButtonHP = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButtonHP.setAutoExclusive(True)
        self.toolButtonHP.setObjectName("toolButtonHP")
        self.horizontalLayout.addWidget(self.toolButtonHP)
        self.toolButtonTS = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButtonTS.setAutoExclusive(True)
        self.toolButtonTS.setObjectName("toolButtonTS")
        self.horizontalLayout.addWidget(self.toolButtonTS)
        self.toolButtonMS = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButtonMS.setAutoExclusive(True)
        self.toolButtonMS.setObjectName("toolButtonMS")
        self.horizontalLayout.addWidget(self.toolButtonMS)
        self.toolButtonArt = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButtonArt.setAutoExclusive(True)
        self.toolButtonArt.setObjectName("toolButtonArt")
        self.horizontalLayout.addWidget(self.toolButtonArt)
        self.stackedWidgetAllPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidgetAllPages.setGeometry(QtCore.QRect(-1, 49, 901, 541))
        self.stackedWidgetAllPages.setObjectName("stackedWidgetAllPages")
        self.pageWelcomeHome = QtWidgets.QWidget()
        self.pageWelcomeHome.setObjectName("pageWelcomeHome")
        self.textWelcome = QtWidgets.QTextBrowser(self.pageWelcomeHome)
        self.textWelcome.setGeometry(QtCore.QRect(200, 130, 511, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 168, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 168, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 168, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 168, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textWelcome.setPalette(palette)
        self.textWelcome.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textWelcome.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textWelcome.setLineWidth(1)
        self.textWelcome.setMidLineWidth(0)
        self.textWelcome.setAcceptRichText(True)
        self.textWelcome.setObjectName("textWelcome")
        self.stackedWidgetAllPages.addWidget(self.pageWelcomeHome)
        self.pageCP = QtWidgets.QWidget()
        self.pageCP.setObjectName("pageCP")
        self.tabsIn_pageCP = QtWidgets.QTabWidget(self.pageCP)
        self.tabsIn_pageCP.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.tabsIn_pageCP.setObjectName("tabsIn_pageCP")
        self.tabCPSteinerGrids = QtWidgets.QWidget()
        self.tabCPSteinerGrids.setObjectName("tabCPSteinerGrids")
        self.tabsIn_pageCP.addTab(self.tabCPSteinerGrids, "")
        self.tabCPMobiusTransformations = QtWidgets.QWidget()
        self.tabCPMobiusTransformations.setObjectName("tabCPMobiusTransformations")
        self.tabsIn_pageCP.addTab(self.tabCPMobiusTransformations, "")
        self.stackedWidgetIn_pageCP = QtWidgets.QStackedWidget(self.pageCP)
        self.stackedWidgetIn_pageCP.setGeometry(QtCore.QRect(620, 20, 281, 491))
        self.stackedWidgetIn_pageCP.setObjectName("stackedWidgetIn_pageCP")
        self.pageCPSteinerGrids = QtWidgets.QWidget()
        self.pageCPSteinerGrids.setObjectName("pageCPSteinerGrids")
        self.pushButtonCPSGCommon = QtWidgets.QPushButton(self.pageCPSteinerGrids)
        self.pushButtonCPSGCommon.setGeometry(QtCore.QRect(10, 80, 171, 32))
        self.pushButtonCPSGCommon.setObjectName("pushButtonCPSGCommon")
        self.spinBoxCPSGCommon = QtWidgets.QSpinBox(self.pageCPSteinerGrids)
        self.spinBoxCPSGCommon.setGeometry(QtCore.QRect(190, 50, 48, 24))
        self.spinBoxCPSGCommon.setWrapping(True)
        self.spinBoxCPSGCommon.setMinimum(2)
        self.spinBoxCPSGCommon.setSingleStep(1)
        self.spinBoxCPSGCommon.setProperty("value", 10)
        self.spinBoxCPSGCommon.setDisplayIntegerBase(10)
        self.spinBoxCPSGCommon.setObjectName("spinBoxCPSGCommon")
        self.lineEditCPSGComplexNumber2 = QtWidgets.QLineEdit(self.pageCPSteinerGrids)
        self.lineEditCPSGComplexNumber2.setGeometry(QtCore.QRect(100, 50, 71, 21))
        self.lineEditCPSGComplexNumber2.setObjectName("lineEditCPSGComplexNumber2")
        self.lineEditCPSGComplexNumber1 = QtWidgets.QLineEdit(self.pageCPSteinerGrids)
        self.lineEditCPSGComplexNumber1.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.lineEditCPSGComplexNumber1.setText("")
        self.lineEditCPSGComplexNumber1.setObjectName("lineEditCPSGComplexNumber1")
        self.pushButtonCPSGApollonius = QtWidgets.QPushButton(self.pageCPSteinerGrids)
        self.pushButtonCPSGApollonius.setGeometry(QtCore.QRect(10, 110, 171, 32))
        self.pushButtonCPSGApollonius.setObjectName("pushButtonCPSGApollonius")
        self.pushButtonCPSGSteiner = QtWidgets.QPushButton(self.pageCPSteinerGrids)
        self.pushButtonCPSGSteiner.setGeometry(QtCore.QRect(10, 140, 171, 32))
        self.pushButtonCPSGSteiner.setObjectName("pushButtonCPSGSteiner")
        self.horizontalSliderCPSGLoxodromesAngleTheta = QtWidgets.QSlider(self.pageCPSteinerGrids)
        self.horizontalSliderCPSGLoxodromesAngleTheta.setEnabled(True)
        self.horizontalSliderCPSGLoxodromesAngleTheta.setGeometry(QtCore.QRect(14, 184, 160, 22))
        self.horizontalSliderCPSGLoxodromesAngleTheta.setMinimum(-1)
        self.horizontalSliderCPSGLoxodromesAngleTheta.setMaximum(360)
        self.horizontalSliderCPSGLoxodromesAngleTheta.setProperty("value", -1)
        self.horizontalSliderCPSGLoxodromesAngleTheta.setSliderPosition(-1)
        self.horizontalSliderCPSGLoxodromesAngleTheta.setTracking(True)
        self.horizontalSliderCPSGLoxodromesAngleTheta.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCPSGLoxodromesAngleTheta.setObjectName("horizontalSliderCPSGLoxodromesAngleTheta")
        self.labelCPSGLoxodromes = QtWidgets.QLabel(self.pageCPSteinerGrids)
        self.labelCPSGLoxodromes.setGeometry(QtCore.QRect(44, 210, 108, 20))
        self.labelCPSGLoxodromes.setObjectName("labelCPSGLoxodromes")
        self.horizontalSliderCPSGLoxodromesAngleTheta.raise_()
        self.pushButtonCPSGCommon.raise_()
        self.spinBoxCPSGCommon.raise_()
        self.lineEditCPSGComplexNumber2.raise_()
        self.lineEditCPSGComplexNumber1.raise_()
        self.pushButtonCPSGApollonius.raise_()
        self.pushButtonCPSGSteiner.raise_()
        self.labelCPSGLoxodromes.raise_()
        self.stackedWidgetIn_pageCP.addWidget(self.pageCPSteinerGrids)
        self.pageCPMobiusTransformations = QtWidgets.QWidget()
        self.pageCPMobiusTransformations.setObjectName("pageCPMobiusTransformations")
        self.frameCPMTOrbits = QtWidgets.QFrame(self.pageCPMobiusTransformations)
        self.frameCPMTOrbits.setGeometry(QtCore.QRect(0, 269, 281, 221))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.frameCPMTOrbits.setFont(font)
        self.frameCPMTOrbits.setAutoFillBackground(False)
        self.frameCPMTOrbits.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameCPMTOrbits.setObjectName("frameCPMTOrbits")
        self.lineEditCPMTOrbitsComplexNumberalpha = QtWidgets.QLineEdit(self.frameCPMTOrbits)
        self.lineEditCPMTOrbitsComplexNumberalpha.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.lineEditCPMTOrbitsComplexNumberalpha.setText("")
        self.lineEditCPMTOrbitsComplexNumberalpha.setObjectName("lineEditCPMTOrbitsComplexNumberalpha")
        self.lineEditCPMTOrbitsComplexNumberbeta = QtWidgets.QLineEdit(self.frameCPMTOrbits)
        self.lineEditCPMTOrbitsComplexNumberbeta.setGeometry(QtCore.QRect(110, 10, 71, 21))
        self.lineEditCPMTOrbitsComplexNumberbeta.setText("")
        self.lineEditCPMTOrbitsComplexNumberbeta.setObjectName("lineEditCPMTOrbitsComplexNumberbeta")
        self.lineEditCPMTOrbitsComplexNumbergamma = QtWidgets.QLineEdit(self.frameCPMTOrbits)
        self.lineEditCPMTOrbitsComplexNumbergamma.setGeometry(QtCore.QRect(30, 40, 71, 21))
        self.lineEditCPMTOrbitsComplexNumbergamma.setText("")
        self.lineEditCPMTOrbitsComplexNumbergamma.setObjectName("lineEditCPMTOrbitsComplexNumbergamma")
        self.lineEditCPMTOrbitsComplexNumberdelta = QtWidgets.QLineEdit(self.frameCPMTOrbits)
        self.lineEditCPMTOrbitsComplexNumberdelta.setGeometry(QtCore.QRect(110, 40, 71, 21))
        self.lineEditCPMTOrbitsComplexNumberdelta.setFrame(True)
        self.lineEditCPMTOrbitsComplexNumberdelta.setClearButtonEnabled(False)
        self.lineEditCPMTOrbitsComplexNumberdelta.setObjectName("lineEditCPMTOrbitsComplexNumberdelta")
        self.lineEditCPMTOrbitsComplexNumberz_0 = QtWidgets.QLineEdit(self.frameCPMTOrbits)
        self.lineEditCPMTOrbitsComplexNumberz_0.setGeometry(QtCore.QRect(30, 74, 71, 21))
        self.lineEditCPMTOrbitsComplexNumberz_0.setObjectName("lineEditCPMTOrbitsComplexNumberz_0")
        self.spinBoxCPMTOrbits = QtWidgets.QSpinBox(self.frameCPMTOrbits)
        self.spinBoxCPMTOrbits.setGeometry(QtCore.QRect(210, 23, 48, 24))
        self.spinBoxCPMTOrbits.setWrapping(True)
        self.spinBoxCPMTOrbits.setMinimum(-99)
        self.spinBoxCPMTOrbits.setProperty("value", 10)
        self.spinBoxCPMTOrbits.setObjectName("spinBoxCPMTOrbits")
        self.pushButtonCPMTOrbitsSinglePoint = QtWidgets.QPushButton(self.frameCPMTOrbits)
        self.pushButtonCPMTOrbitsSinglePoint.setGeometry(QtCore.QRect(160, 70, 113, 32))
        self.pushButtonCPMTOrbitsSinglePoint.setObjectName("pushButtonCPMTOrbitsSinglePoint")
        self.lineCPMTOrbits_1 = QtWidgets.QFrame(self.frameCPMTOrbits)
        self.lineCPMTOrbits_1.setGeometry(QtCore.QRect(8, 60, 261, 16))
        self.lineCPMTOrbits_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineCPMTOrbits_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineCPMTOrbits_1.setObjectName("lineCPMTOrbits_1")
        self.lineCPMTOrbits_2 = QtWidgets.QFrame(self.frameCPMTOrbits)
        self.lineCPMTOrbits_2.setGeometry(QtCore.QRect(10, 94, 261, 16))
        self.lineCPMTOrbits_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineCPMTOrbits_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineCPMTOrbits_2.setObjectName("lineCPMTOrbits_2")
        self.pushButtonCPMTOrbitsRandomCircle = QtWidgets.QPushButton(self.frameCPMTOrbits)
        self.pushButtonCPMTOrbitsRandomCircle.setGeometry(QtCore.QRect(160, 108, 113, 32))
        self.pushButtonCPMTOrbitsRandomCircle.setObjectName("pushButtonCPMTOrbitsRandomCircle")
        self.pushButtonCPMTOrbitsSteinerGrid = QtWidgets.QPushButton(self.frameCPMTOrbits)
        self.pushButtonCPMTOrbitsSteinerGrid.setGeometry(QtCore.QRect(161, 143, 113, 32))
        self.pushButtonCPMTOrbitsSteinerGrid.setObjectName("pushButtonCPMTOrbitsSteinerGrid")
        self.stackedWidgetIn_pageCP.addWidget(self.pageCPMobiusTransformations)
        self.pushButtonCPClearCanvas = QtWidgets.QPushButton(self.pageCP)
        self.pushButtonCPClearCanvas.setGeometry(QtCore.QRect(250, 510, 113, 32))
        self.pushButtonCPClearCanvas.setObjectName("pushButtonCPClearCanvas")
        self.PlotWidgetIn_pageCP = PlotWidget(self.pageCP)
        self.PlotWidgetIn_pageCP.setEnabled(True)
        self.PlotWidgetIn_pageCP.setGeometry(QtCore.QRect(1, 21, 618, 489))
        self.PlotWidgetIn_pageCP.setObjectName("PlotWidgetIn_pageCP")
        self.radioButtonCPoo = QtWidgets.QRadioButton(self.pageCP)
        self.radioButtonCPoo.setEnabled(True)
        self.radioButtonCPoo.setGeometry(QtCore.QRect(579, 22, 38, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.radioButtonCPoo.setPalette(palette)
        self.radioButtonCPoo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButtonCPoo.setCheckable(True)
        self.radioButtonCPoo.setChecked(False)
        self.radioButtonCPoo.setObjectName("radioButtonCPoo")
        self.stackedWidgetAllPages.addWidget(self.pageCP)
        self.pageHP = QtWidgets.QWidget()
        self.pageHP.setObjectName("pageHP")
        self.tabsIn_pageHP = QtWidgets.QTabWidget(self.pageHP)
        self.tabsIn_pageHP.setGeometry(QtCore.QRect(0, 0, 901, 541))
        self.tabsIn_pageHP.setStatusTip("")
        self.tabsIn_pageHP.setObjectName("tabsIn_pageHP")
        self.tabUHP = QtWidgets.QWidget()
        self.tabUHP.setObjectName("tabUHP")
        self.tabsIn_tabUHP = QtWidgets.QTabWidget(self.tabUHP)
        self.tabsIn_tabUHP.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.tabsIn_tabUHP.setObjectName("tabsIn_tabUHP")
        self.tabUHPBasicConstructions = QtWidgets.QWidget()
        self.tabUHPBasicConstructions.setObjectName("tabUHPBasicConstructions")
        self.tabsIn_tabUHP.addTab(self.tabUHPBasicConstructions, "")
        self.tabUHPGeodesicMotion = QtWidgets.QWidget()
        self.tabUHPGeodesicMotion.setObjectName("tabUHPGeodesicMotion")
        self.tabsIn_tabUHP.addTab(self.tabUHPGeodesicMotion, "")
        self.tabUHPCircularMotion = QtWidgets.QWidget()
        self.tabUHPCircularMotion.setObjectName("tabUHPCircularMotion")
        self.tabsIn_tabUHP.addTab(self.tabUHPCircularMotion, "")
        self.tabUHPIsometries = QtWidgets.QWidget()
        self.tabUHPIsometries.setObjectName("tabUHPIsometries")
        self.tabsIn_tabUHP.addTab(self.tabUHPIsometries, "")
        self.PlotWidgetIn_pageUHP = PlotWidget(self.tabUHP)
        self.PlotWidgetIn_pageUHP.setEnabled(True)
        self.PlotWidgetIn_pageUHP.setGeometry(QtCore.QRect(0, 20, 618, 464))
        self.PlotWidgetIn_pageUHP.setMouseTracking(True)
        self.PlotWidgetIn_pageUHP.setObjectName("PlotWidgetIn_pageUHP")
        self.radioButtonCPoo_2 = QtWidgets.QRadioButton(self.tabUHP)
        self.radioButtonCPoo_2.setEnabled(True)
        self.radioButtonCPoo_2.setGeometry(QtCore.QRect(576, 22, 38, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.radioButtonCPoo_2.setPalette(palette)
        self.radioButtonCPoo_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButtonCPoo_2.setCheckable(True)
        self.radioButtonCPoo_2.setChecked(False)
        self.radioButtonCPoo_2.setObjectName("radioButtonCPoo_2")
        self.pushButtonUHPClearCanvas = QtWidgets.QPushButton(self.tabUHP)
        self.pushButtonUHPClearCanvas.setGeometry(QtCore.QRect(247, 485, 113, 32))
        self.pushButtonUHPClearCanvas.setObjectName("pushButtonUHPClearCanvas")
        self.stackedWidgetIn_pageUHP = QtWidgets.QStackedWidget(self.tabUHP)
        self.stackedWidgetIn_pageUHP.setGeometry(QtCore.QRect(616, 23, 282, 461))
        self.stackedWidgetIn_pageUHP.setObjectName("stackedWidgetIn_pageUHP")
        self.pageUHPBasicConstructions = QtWidgets.QWidget()
        self.pageUHPBasicConstructions.setObjectName("pageUHPBasicConstructions")
        self.labelUHPBChdistance = QtWidgets.QLabel(self.pageUHPBasicConstructions)
        self.labelUHPBChdistance.setGeometry(QtCore.QRect(17, 75, 71, 16))
        self.labelUHPBChdistance.setObjectName("labelUHPBChdistance")
        self.pushButtonUHPBCShowGeodesicSegment = QtWidgets.QPushButton(self.pageUHPBasicConstructions)
        self.pushButtonUHPBCShowGeodesicSegment.setGeometry(QtCore.QRect(199, 45, 78, 32))
        self.pushButtonUHPBCShowGeodesicSegment.setObjectName("pushButtonUHPBCShowGeodesicSegment")
        self.labelUHPBCto = QtWidgets.QLabel(self.pageUHPBasicConstructions)
        self.labelUHPBCto.setGeometry(QtCore.QRect(107, 30, 23, 16))
        self.labelUHPBCto.setObjectName("labelUHPBCto")
        self.labelUHPBCfrom = QtWidgets.QLabel(self.pageUHPBasicConstructions)
        self.labelUHPBCfrom.setGeometry(QtCore.QRect(17, 30, 39, 16))
        self.labelUHPBCfrom.setObjectName("labelUHPBCfrom")
        self.lineEditUHPBCComplexNumber1 = QtWidgets.QLineEdit(self.pageUHPBasicConstructions)
        self.lineEditUHPBCComplexNumber1.setGeometry(QtCore.QRect(16, 49, 71, 21))
        self.lineEditUHPBCComplexNumber1.setText("")
        self.lineEditUHPBCComplexNumber1.setObjectName("lineEditUHPBCComplexNumber1")
        self.lineEditUHPBCComplexNumber2 = QtWidgets.QLineEdit(self.pageUHPBasicConstructions)
        self.lineEditUHPBCComplexNumber2.setGeometry(QtCore.QRect(106, 49, 71, 21))
        self.lineEditUHPBCComplexNumber2.setObjectName("lineEditUHPBCComplexNumber2")
        self.labelUHPBChdistancenumber = QtWidgets.QLabel(self.pageUHPBasicConstructions)
        self.labelUHPBChdistancenumber.setGeometry(QtCore.QRect(90, 75, 79, 16))
        self.labelUHPBChdistancenumber.setObjectName("labelUHPBChdistancenumber")
        self.radioButtonUHPBCGeodesicSegments = QtWidgets.QRadioButton(self.pageUHPBasicConstructions)
        self.radioButtonUHPBCGeodesicSegments.setGeometry(QtCore.QRect(5, 10, 141, 20))
        self.radioButtonUHPBCGeodesicSegments.setObjectName("radioButtonUHPBCGeodesicSegments")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButtonUHPBCGeodesicSegments)
        self.radioButtonUHPBCConvexHull = QtWidgets.QRadioButton(self.pageUHPBasicConstructions)
        self.radioButtonUHPBCConvexHull.setGeometry(QtCore.QRect(5, 100, 100, 20))
        self.radioButtonUHPBCConvexHull.setObjectName("radioButtonUHPBCConvexHull")
        self.buttonGroup.addButton(self.radioButtonUHPBCConvexHull)
        self.stackedWidgetIn_pageUHP.addWidget(self.pageUHPBasicConstructions)
        self.pageUHPGeodesicMotion = QtWidgets.QWidget()
        self.pageUHPGeodesicMotion.setObjectName("pageUHPGeodesicMotion")
        self.pushButtonUHPGMShowGeodesic = QtWidgets.QPushButton(self.pageUHPGeodesicMotion)
        self.pushButtonUHPGMShowGeodesic.setGeometry(QtCore.QRect(199, 45, 78, 32))
        self.pushButtonUHPGMShowGeodesic.setObjectName("pushButtonUHPGMShowGeodesic")
        self.lineEditUHPGMComplexNumber1 = QtWidgets.QLineEdit(self.pageUHPGeodesicMotion)
        self.lineEditUHPGMComplexNumber1.setGeometry(QtCore.QRect(16, 49, 71, 21))
        self.lineEditUHPGMComplexNumber1.setText("")
        self.lineEditUHPGMComplexNumber1.setObjectName("lineEditUHPGMComplexNumber1")
        self.lineEditUHPGMComplexNumber2 = QtWidgets.QLineEdit(self.pageUHPGeodesicMotion)
        self.lineEditUHPGMComplexNumber2.setGeometry(QtCore.QRect(106, 49, 71, 21))
        self.lineEditUHPGMComplexNumber2.setObjectName("lineEditUHPGMComplexNumber2")
        self.labelUHPGMhdistance = QtWidgets.QLabel(self.pageUHPGeodesicMotion)
        self.labelUHPGMhdistance.setGeometry(QtCore.QRect(17, 75, 71, 16))
        self.labelUHPGMhdistance.setObjectName("labelUHPGMhdistance")
        self.labelUHPGMhdistancenumber = QtWidgets.QLabel(self.pageUHPGeodesicMotion)
        self.labelUHPGMhdistancenumber.setGeometry(QtCore.QRect(90, 75, 79, 16))
        self.labelUHPGMhdistancenumber.setObjectName("labelUHPGMhdistancenumber")
        self.labelUHPGMfrom = QtWidgets.QLabel(self.pageUHPGeodesicMotion)
        self.labelUHPGMfrom.setGeometry(QtCore.QRect(17, 30, 39, 16))
        self.labelUHPGMfrom.setObjectName("labelUHPGMfrom")
        self.labelUHPGMto = QtWidgets.QLabel(self.pageUHPGeodesicMotion)
        self.labelUHPGMto.setGeometry(QtCore.QRect(107, 30, 23, 16))
        self.labelUHPGMto.setObjectName("labelUHPGMto")
        self.PlotWidgetIn_pageUHPGeodesicMotion = PlotWidget(self.pageUHPGeodesicMotion)
        self.PlotWidgetIn_pageUHPGeodesicMotion.setGeometry(QtCore.QRect(2, 310, 150, 150))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.PlotWidgetIn_pageUHPGeodesicMotion.setBackgroundBrush(brush)
        self.PlotWidgetIn_pageUHPGeodesicMotion.setObjectName("PlotWidgetIn_pageUHPGeodesicMotion")
        self.radioButtonUHPGMPointPoint = QtWidgets.QRadioButton(self.pageUHPGeodesicMotion)
        self.radioButtonUHPGMPointPoint.setGeometry(QtCore.QRect(17, 95, 111, 20))
        self.radioButtonUHPGMPointPoint.setObjectName("radioButtonUHPGMPointPoint")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButtonUHPGMPointPoint)
        self.radioButtonUHPGMPointVector = QtWidgets.QRadioButton(self.pageUHPGeodesicMotion)
        self.radioButtonUHPGMPointVector.setGeometry(QtCore.QRect(17, 115, 100, 20))
        self.radioButtonUHPGMPointVector.setObjectName("radioButtonUHPGMPointVector")
        self.buttonGroup_2.addButton(self.radioButtonUHPGMPointVector)
        self.radioButtonUHPGMGeoParamByArcLength = QtWidgets.QRadioButton(self.pageUHPGeodesicMotion)
        self.radioButtonUHPGMGeoParamByArcLength.setGeometry(QtCore.QRect(5, 10, 221, 20))
        self.radioButtonUHPGMGeoParamByArcLength.setObjectName("radioButtonUHPGMGeoParamByArcLength")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButtonUHPGMGeoParamByArcLength)
        self.radioButtonUHPGMWaves = QtWidgets.QRadioButton(self.pageUHPGeodesicMotion)
        self.radioButtonUHPGMWaves.setGeometry(QtCore.QRect(5, 140, 61, 20))
        self.radioButtonUHPGMWaves.setObjectName("radioButtonUHPGMWaves")
        self.buttonGroup_3.addButton(self.radioButtonUHPGMWaves)
        self.spinBoxUHPGMWaveRapidity = QtWidgets.QSpinBox(self.pageUHPGeodesicMotion)
        self.spinBoxUHPGMWaveRapidity.setGeometry(QtCore.QRect(17, 160, 48, 24))
        self.spinBoxUHPGMWaveRapidity.setMinimum(1)
        self.spinBoxUHPGMWaveRapidity.setObjectName("spinBoxUHPGMWaveRapidity")
        self.stackedWidgetIn_pageUHP.addWidget(self.pageUHPGeodesicMotion)
        self.pageUHPCircularMotion = QtWidgets.QWidget()
        self.pageUHPCircularMotion.setObjectName("pageUHPCircularMotion")
        self.pushButtonUHPCMCircMotionAntiClockwise = QtWidgets.QPushButton(self.pageUHPCircularMotion)
        self.pushButtonUHPCMCircMotionAntiClockwise.setGeometry(QtCore.QRect(10, 10, 113, 32))
        self.pushButtonUHPCMCircMotionAntiClockwise.setObjectName("pushButtonUHPCMCircMotionAntiClockwise")
        self.stackedWidgetIn_pageUHP.addWidget(self.pageUHPCircularMotion)
        self.pageUHPIsometries = QtWidgets.QWidget()
        self.pageUHPIsometries.setObjectName("pageUHPIsometries")
        self.stackedWidgetIn_pageUHP.addWidget(self.pageUHPIsometries)
        self.labelUHPyNumber = QtWidgets.QLabel(self.tabUHP)
        self.labelUHPyNumber.setGeometry(QtCore.QRect(10, 498, 180, 16))
        self.labelUHPyNumber.setObjectName("labelUHPyNumber")
        self.labelUHPxNumber = QtWidgets.QLabel(self.tabUHP)
        self.labelUHPxNumber.setGeometry(QtCore.QRect(10, 485, 180, 16))
        self.labelUHPxNumber.setObjectName("labelUHPxNumber")
        self.tabsIn_pageHP.addTab(self.tabUHP, "")
        self.tabPD = QtWidgets.QWidget()
        self.tabPD.setObjectName("tabPD")
        self.tabsIn_tabPD = QtWidgets.QTabWidget(self.tabPD)
        self.tabsIn_tabPD.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.tabsIn_tabPD.setObjectName("tabsIn_tabPD")
        self.tabPDBasicConstructions = QtWidgets.QWidget()
        self.tabPDBasicConstructions.setObjectName("tabPDBasicConstructions")
        self.tabsIn_tabPD.addTab(self.tabPDBasicConstructions, "")
        self.tabPDGeodesicMotion = QtWidgets.QWidget()
        self.tabPDGeodesicMotion.setObjectName("tabPDGeodesicMotion")
        self.tabsIn_tabPD.addTab(self.tabPDGeodesicMotion, "")
        self.tabPDCircularMotion = QtWidgets.QWidget()
        self.tabPDCircularMotion.setObjectName("tabPDCircularMotion")
        self.tabsIn_tabPD.addTab(self.tabPDCircularMotion, "")
        self.tabPDIsometries = QtWidgets.QWidget()
        self.tabPDIsometries.setObjectName("tabPDIsometries")
        self.tabsIn_tabPD.addTab(self.tabPDIsometries, "")
        self.PlotWidgetIn_pagePD = PlotWidget(self.tabPD)
        self.PlotWidgetIn_pagePD.setEnabled(True)
        self.PlotWidgetIn_pagePD.setGeometry(QtCore.QRect(0, 20, 464, 464))
        self.PlotWidgetIn_pagePD.setMouseTracking(True)
        self.PlotWidgetIn_pagePD.setObjectName("PlotWidgetIn_pagePD")
        self.stackedWidgetIn_pagePD = QtWidgets.QStackedWidget(self.tabPD)
        self.stackedWidgetIn_pagePD.setGeometry(QtCore.QRect(616, 51, 282, 433))
        self.stackedWidgetIn_pagePD.setObjectName("stackedWidgetIn_pagePD")
        self.pageUHPBasicConstructions_2 = QtWidgets.QWidget()
        self.pageUHPBasicConstructions_2.setObjectName("pageUHPBasicConstructions_2")
        self.labelPDBChdistance = QtWidgets.QLabel(self.pageUHPBasicConstructions_2)
        self.labelPDBChdistance.setGeometry(QtCore.QRect(9, 80, 71, 16))
        self.labelPDBChdistance.setObjectName("labelPDBChdistance")
        self.pushButtonPDBCShowGeodesicSegment = QtWidgets.QPushButton(self.pageUHPBasicConstructions_2)
        self.pushButtonPDBCShowGeodesicSegment.setGeometry(QtCore.QRect(192, 45, 78, 32))
        self.pushButtonPDBCShowGeodesicSegment.setObjectName("pushButtonPDBCShowGeodesicSegment")
        self.labelPDBCto = QtWidgets.QLabel(self.pageUHPBasicConstructions_2)
        self.labelPDBCto.setGeometry(QtCore.QRect(100, 30, 23, 16))
        self.labelPDBCto.setObjectName("labelPDBCto")
        self.labelPDBCfrom = QtWidgets.QLabel(self.pageUHPBasicConstructions_2)
        self.labelPDBCfrom.setGeometry(QtCore.QRect(10, 30, 39, 16))
        self.labelPDBCfrom.setObjectName("labelPDBCfrom")
        self.lineEditPDBCComplexNumber1 = QtWidgets.QLineEdit(self.pageUHPBasicConstructions_2)
        self.lineEditPDBCComplexNumber1.setGeometry(QtCore.QRect(9, 49, 71, 21))
        self.lineEditPDBCComplexNumber1.setText("")
        self.lineEditPDBCComplexNumber1.setObjectName("lineEditPDBCComplexNumber1")
        self.lineEditPDBCComplexNumber2 = QtWidgets.QLineEdit(self.pageUHPBasicConstructions_2)
        self.lineEditPDBCComplexNumber2.setGeometry(QtCore.QRect(99, 49, 71, 21))
        self.lineEditPDBCComplexNumber2.setObjectName("lineEditPDBCComplexNumber2")
        self.labelPDBChdistancenumber = QtWidgets.QLabel(self.pageUHPBasicConstructions_2)
        self.labelPDBChdistancenumber.setGeometry(QtCore.QRect(82, 80, 79, 16))
        self.labelPDBChdistancenumber.setObjectName("labelPDBChdistancenumber")
        self.stackedWidgetIn_pagePD.addWidget(self.pageUHPBasicConstructions_2)
        self.pageUHPGeodesicMotion_2 = QtWidgets.QWidget()
        self.pageUHPGeodesicMotion_2.setObjectName("pageUHPGeodesicMotion_2")
        self.pushButtonPDGMShowGeodesic = QtWidgets.QPushButton(self.pageUHPGeodesicMotion_2)
        self.pushButtonPDGMShowGeodesic.setGeometry(QtCore.QRect(192, 45, 78, 32))
        self.pushButtonPDGMShowGeodesic.setObjectName("pushButtonPDGMShowGeodesic")
        self.lineEditPDGMComplexNumber1 = QtWidgets.QLineEdit(self.pageUHPGeodesicMotion_2)
        self.lineEditPDGMComplexNumber1.setGeometry(QtCore.QRect(9, 49, 71, 21))
        self.lineEditPDGMComplexNumber1.setText("")
        self.lineEditPDGMComplexNumber1.setObjectName("lineEditPDGMComplexNumber1")
        self.lineEditPDGMComplexNumber2 = QtWidgets.QLineEdit(self.pageUHPGeodesicMotion_2)
        self.lineEditPDGMComplexNumber2.setGeometry(QtCore.QRect(99, 49, 71, 21))
        self.lineEditPDGMComplexNumber2.setObjectName("lineEditPDGMComplexNumber2")
        self.labelPDGMhdistance = QtWidgets.QLabel(self.pageUHPGeodesicMotion_2)
        self.labelPDGMhdistance.setGeometry(QtCore.QRect(9, 80, 71, 16))
        self.labelPDGMhdistance.setObjectName("labelPDGMhdistance")
        self.labelPDGMhdistancenumber = QtWidgets.QLabel(self.pageUHPGeodesicMotion_2)
        self.labelPDGMhdistancenumber.setGeometry(QtCore.QRect(82, 80, 79, 16))
        self.labelPDGMhdistancenumber.setObjectName("labelPDGMhdistancenumber")
        self.labelPDGMfrom = QtWidgets.QLabel(self.pageUHPGeodesicMotion_2)
        self.labelPDGMfrom.setGeometry(QtCore.QRect(10, 30, 39, 16))
        self.labelPDGMfrom.setObjectName("labelPDGMfrom")
        self.labelPDGMto = QtWidgets.QLabel(self.pageUHPGeodesicMotion_2)
        self.labelPDGMto.setGeometry(QtCore.QRect(100, 30, 23, 16))
        self.labelPDGMto.setObjectName("labelPDGMto")
        self.stackedWidgetIn_pagePD.addWidget(self.pageUHPGeodesicMotion_2)
        self.pageUHPCircularMotion_2 = QtWidgets.QWidget()
        self.pageUHPCircularMotion_2.setObjectName("pageUHPCircularMotion_2")
        self.pushButtonPDCMCircMotionAntiClockwise = QtWidgets.QPushButton(self.pageUHPCircularMotion_2)
        self.pushButtonPDCMCircMotionAntiClockwise.setGeometry(QtCore.QRect(10, 10, 113, 32))
        self.pushButtonPDCMCircMotionAntiClockwise.setObjectName("pushButtonPDCMCircMotionAntiClockwise")
        self.stackedWidgetIn_pagePD.addWidget(self.pageUHPCircularMotion_2)
        self.pageUHPIsometries_2 = QtWidgets.QWidget()
        self.pageUHPIsometries_2.setObjectName("pageUHPIsometries_2")
        self.stackedWidgetIn_pagePD.addWidget(self.pageUHPIsometries_2)
        self.checkBoxPDEnableClickOnCanvas = QtWidgets.QCheckBox(self.tabPD)
        self.checkBoxPDEnableClickOnCanvas.setGeometry(QtCore.QRect(620, 24, 180, 20))
        self.checkBoxPDEnableClickOnCanvas.setTristate(False)
        self.checkBoxPDEnableClickOnCanvas.setObjectName("checkBoxPDEnableClickOnCanvas")
        self.labelPDyNumber = QtWidgets.QLabel(self.tabPD)
        self.labelPDyNumber.setGeometry(QtCore.QRect(10, 498, 150, 16))
        self.labelPDyNumber.setObjectName("labelPDyNumber")
        self.labelPDxNumber = QtWidgets.QLabel(self.tabPD)
        self.labelPDxNumber.setGeometry(QtCore.QRect(10, 485, 150, 16))
        self.labelPDxNumber.setObjectName("labelPDxNumber")
        self.labelPDNormNumber = QtWidgets.QLabel(self.tabPD)
        self.labelPDNormNumber.setGeometry(QtCore.QRect(300, 485, 150, 16))
        self.labelPDNormNumber.setObjectName("labelPDNormNumber")
        self.pushButtonPDClearCanvas = QtWidgets.QPushButton(self.tabPD)
        self.pushButtonPDClearCanvas.setGeometry(QtCore.QRect(175, 485, 113, 32))
        self.pushButtonPDClearCanvas.setObjectName("pushButtonPDClearCanvas")
        self.tabsIn_pageHP.addTab(self.tabPD, "")
        self.tabHyper = QtWidgets.QWidget()
        self.tabHyper.setObjectName("tabHyper")
        self.tabsIn_tabHyper = QtWidgets.QTabWidget(self.tabHyper)
        self.tabsIn_tabHyper.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.tabsIn_tabHyper.setObjectName("tabsIn_tabHyper")
        self.tabHyperBasicConstructions = QtWidgets.QWidget()
        self.tabHyperBasicConstructions.setObjectName("tabHyperBasicConstructions")
        self.tabsIn_tabHyper.addTab(self.tabHyperBasicConstructions, "")
        self.tabHyperGeodesicMotion = QtWidgets.QWidget()
        self.tabHyperGeodesicMotion.setObjectName("tabHyperGeodesicMotion")
        self.tabsIn_tabHyper.addTab(self.tabHyperGeodesicMotion, "")
        self.tabHyperCircularMotion = QtWidgets.QWidget()
        self.tabHyperCircularMotion.setObjectName("tabHyperCircularMotion")
        self.tabsIn_tabHyper.addTab(self.tabHyperCircularMotion, "")
        self.tabHyperIsometries = QtWidgets.QWidget()
        self.tabHyperIsometries.setObjectName("tabHyperIsometries")
        self.tabsIn_tabHyper.addTab(self.tabHyperIsometries, "")
        self.openGLWidget = GLViewWidget(self.tabHyper)
        self.openGLWidget.setGeometry(QtCore.QRect(0, 20, 618, 464))
        self.openGLWidget.setObjectName("openGLWidget")
        self.tabsIn_pageHP.addTab(self.tabHyper, "")
        self.tabUHPandPD = QtWidgets.QWidget()
        self.tabUHPandPD.setObjectName("tabUHPandPD")
        self.tabsIn_tabUHPandPD = QtWidgets.QTabWidget(self.tabUHPandPD)
        self.tabsIn_tabUHPandPD.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.tabsIn_tabUHPandPD.setObjectName("tabsIn_tabUHPandPD")
        self.tabUHPandPDBasicConstructions = QtWidgets.QWidget()
        self.tabUHPandPDBasicConstructions.setObjectName("tabUHPandPDBasicConstructions")
        self.tabsIn_tabUHPandPD.addTab(self.tabUHPandPDBasicConstructions, "")
        self.tabUHPandPDGeodesicMotion = QtWidgets.QWidget()
        self.tabUHPandPDGeodesicMotion.setObjectName("tabUHPandPDGeodesicMotion")
        self.tabsIn_tabUHPandPD.addTab(self.tabUHPandPDGeodesicMotion, "")
        self.tabUHPandPDCircularMotion = QtWidgets.QWidget()
        self.tabUHPandPDCircularMotion.setObjectName("tabUHPandPDCircularMotion")
        self.tabsIn_tabUHPandPD.addTab(self.tabUHPandPDCircularMotion, "")
        self.tabUHPandPDIsometries = QtWidgets.QWidget()
        self.tabUHPandPDIsometries.setObjectName("tabUHPandPDIsometries")
        self.tabsIn_tabUHPandPD.addTab(self.tabUHPandPDIsometries, "")
        self.mplWidgetIn_tabUHPandPD_Upper = MplWidget(self.tabUHPandPD)
        self.mplWidgetIn_tabUHPandPD_Upper.setGeometry(QtCore.QRect(0, 20, 441, 351))
        self.mplWidgetIn_tabUHPandPD_Upper.setObjectName("mplWidgetIn_tabUHPandPD_Upper")
        self.mplWidgetIn_tabUHPandPD_Poincare = MplWidget(self.tabUHPandPD)
        self.mplWidgetIn_tabUHPandPD_Poincare.setGeometry(QtCore.QRect(450, 20, 441, 351))
        self.mplWidgetIn_tabUHPandPD_Poincare.setObjectName("mplWidgetIn_tabUHPandPD_Poincare")
        self.tabsIn_pageHP.addTab(self.tabUHPandPD, "")
        self.tabUHPandHyper = QtWidgets.QWidget()
        self.tabUHPandHyper.setObjectName("tabUHPandHyper")
        self.tabsIn_tabUHPandHyper = QtWidgets.QTabWidget(self.tabUHPandHyper)
        self.tabsIn_tabUHPandHyper.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.tabsIn_tabUHPandHyper.setObjectName("tabsIn_tabUHPandHyper")
        self.tabUHPandHyperBasicConstructions = QtWidgets.QWidget()
        self.tabUHPandHyperBasicConstructions.setObjectName("tabUHPandHyperBasicConstructions")
        self.tabsIn_tabUHPandHyper.addTab(self.tabUHPandHyperBasicConstructions, "")
        self.tabUHPandHyperGeodesicMotion = QtWidgets.QWidget()
        self.tabUHPandHyperGeodesicMotion.setObjectName("tabUHPandHyperGeodesicMotion")
        self.tabsIn_tabUHPandHyper.addTab(self.tabUHPandHyperGeodesicMotion, "")
        self.tabUHPandHyperCircularMotion = QtWidgets.QWidget()
        self.tabUHPandHyperCircularMotion.setObjectName("tabUHPandHyperCircularMotion")
        self.tabsIn_tabUHPandHyper.addTab(self.tabUHPandHyperCircularMotion, "")
        self.tabUHPandHyperIsometries = QtWidgets.QWidget()
        self.tabUHPandHyperIsometries.setObjectName("tabUHPandHyperIsometries")
        self.tabsIn_tabUHPandHyper.addTab(self.tabUHPandHyperIsometries, "")
        self.mplWidgetIn_tabUHPandHyper_Upper = MplWidget(self.tabUHPandHyper)
        self.mplWidgetIn_tabUHPandHyper_Upper.setGeometry(QtCore.QRect(0, 20, 441, 351))
        self.mplWidgetIn_tabUHPandHyper_Upper.setObjectName("mplWidgetIn_tabUHPandHyper_Upper")
        self.mplWidgetIn_tabUHPandHyper_Hyper = MplWidget(self.tabUHPandHyper)
        self.mplWidgetIn_tabUHPandHyper_Hyper.setGeometry(QtCore.QRect(450, 20, 441, 351))
        self.mplWidgetIn_tabUHPandHyper_Hyper.setObjectName("mplWidgetIn_tabUHPandHyper_Hyper")
        self.tabsIn_pageHP.addTab(self.tabUHPandHyper, "")
        self.tabPDandHyper = QtWidgets.QWidget()
        self.tabPDandHyper.setObjectName("tabPDandHyper")
        self.tabsIn_tabPDandHyper = QtWidgets.QTabWidget(self.tabPDandHyper)
        self.tabsIn_tabPDandHyper.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.tabsIn_tabPDandHyper.setObjectName("tabsIn_tabPDandHyper")
        self.tabPDandHyperBasicConstructions = QtWidgets.QWidget()
        self.tabPDandHyperBasicConstructions.setObjectName("tabPDandHyperBasicConstructions")
        self.tabsIn_tabPDandHyper.addTab(self.tabPDandHyperBasicConstructions, "")
        self.tabPDandHyperGeodesicMotion = QtWidgets.QWidget()
        self.tabPDandHyperGeodesicMotion.setObjectName("tabPDandHyperGeodesicMotion")
        self.tabsIn_tabPDandHyper.addTab(self.tabPDandHyperGeodesicMotion, "")
        self.tabPDandHyperCircularMotion = QtWidgets.QWidget()
        self.tabPDandHyperCircularMotion.setObjectName("tabPDandHyperCircularMotion")
        self.tabsIn_tabPDandHyper.addTab(self.tabPDandHyperCircularMotion, "")
        self.tabPDandHyperIsometries = QtWidgets.QWidget()
        self.tabPDandHyperIsometries.setObjectName("tabPDandHyperIsometries")
        self.tabsIn_tabPDandHyper.addTab(self.tabPDandHyperIsometries, "")
        self.mplWidgetIn_tabPDandHyper_Poincare = MplWidget(self.tabPDandHyper)
        self.mplWidgetIn_tabPDandHyper_Poincare.setGeometry(QtCore.QRect(0, 20, 441, 351))
        self.mplWidgetIn_tabPDandHyper_Poincare.setObjectName("mplWidgetIn_tabPDandHyper_Poincare")
        self.mplWidgetIn_tabPDandHyper_Hyper = MplWidget(self.tabPDandHyper)
        self.mplWidgetIn_tabPDandHyper_Hyper.setGeometry(QtCore.QRect(450, 20, 441, 351))
        self.mplWidgetIn_tabPDandHyper_Hyper.setObjectName("mplWidgetIn_tabPDandHyper_Hyper")
        self.tabsIn_pageHP.addTab(self.tabPDandHyper, "")
        self.tabThreeModels = QtWidgets.QWidget()
        self.tabThreeModels.setObjectName("tabThreeModels")
        self.tabsIn_tabThreeModels = QtWidgets.QTabWidget(self.tabThreeModels)
        self.tabsIn_tabThreeModels.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.tabsIn_tabThreeModels.setObjectName("tabsIn_tabThreeModels")
        self.tabThreeModelsBasicConstructions = QtWidgets.QWidget()
        self.tabThreeModelsBasicConstructions.setObjectName("tabThreeModelsBasicConstructions")
        self.tabsIn_tabThreeModels.addTab(self.tabThreeModelsBasicConstructions, "")
        self.tabThreeModelsGeodesicMotion = QtWidgets.QWidget()
        self.tabThreeModelsGeodesicMotion.setObjectName("tabThreeModelsGeodesicMotion")
        self.tabsIn_tabThreeModels.addTab(self.tabThreeModelsGeodesicMotion, "")
        self.tabThreeModelsCircularMotion = QtWidgets.QWidget()
        self.tabThreeModelsCircularMotion.setObjectName("tabThreeModelsCircularMotion")
        self.tabsIn_tabThreeModels.addTab(self.tabThreeModelsCircularMotion, "")
        self.tabThreeModelsIsometries = QtWidgets.QWidget()
        self.tabThreeModelsIsometries.setObjectName("tabThreeModelsIsometries")
        self.tabsIn_tabThreeModels.addTab(self.tabThreeModelsIsometries, "")
        self.mplWidgetIn_tabThreeModels_Upper = MplWidget(self.tabThreeModels)
        self.mplWidgetIn_tabThreeModels_Upper.setGeometry(QtCore.QRect(0, 20, 291, 271))
        self.mplWidgetIn_tabThreeModels_Upper.setObjectName("mplWidgetIn_tabThreeModels_Upper")
        self.mplWidgetIn_tabThreeModels_Hyper = MplWidget(self.tabThreeModels)
        self.mplWidgetIn_tabThreeModels_Hyper.setGeometry(QtCore.QRect(600, 20, 291, 271))
        self.mplWidgetIn_tabThreeModels_Hyper.setObjectName("mplWidgetIn_tabThreeModels_Hyper")
        self.mplWidgetIn_tabThreeModels_Poincare = MplWidget(self.tabThreeModels)
        self.mplWidgetIn_tabThreeModels_Poincare.setGeometry(QtCore.QRect(300, 20, 291, 271))
        self.mplWidgetIn_tabThreeModels_Poincare.setObjectName("mplWidgetIn_tabThreeModels_Poincare")
        self.tabsIn_pageHP.addTab(self.tabThreeModels, "")
        self.stackedWidgetAllPages.addWidget(self.pageHP)
        self.pageTS = QtWidgets.QWidget()
        self.pageTS.setObjectName("pageTS")
        self.graphicsView = QtWidgets.QGraphicsView(self.pageTS)
        self.graphicsView.setGeometry(QtCore.QRect(384, 102, 360, 336))
        self.graphicsView.setObjectName("graphicsView")
        self.stackedWidgetAllPages.addWidget(self.pageTS)
        self.pageMS = QtWidgets.QWidget()
        self.pageMS.setObjectName("pageMS")
        self.stackedWidgetAllPages.addWidget(self.pageMS)
        self.pageArt = QtWidgets.QWidget()
        self.pageArt.setObjectName("pageArt")
        self.stackedWidgetAllPages.addWidget(self.pageArt)
#        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
 #       MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
  #      MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidgetAllPages.setCurrentIndex(2)
        self.tabsIn_pageCP.setCurrentIndex(0)
        self.stackedWidgetIn_pageCP.setCurrentIndex(0)
        self.tabsIn_pageHP.setCurrentIndex(0)
        self.tabsIn_tabUHP.setCurrentIndex(0)
        self.stackedWidgetIn_pageUHP.setCurrentIndex(1)
        self.tabsIn_tabPD.setCurrentIndex(0)
        self.stackedWidgetIn_pagePD.setCurrentIndex(0)
        self.tabsIn_tabHyper.setCurrentIndex(3)
        self.tabsIn_tabUHPandPD.setCurrentIndex(0)
        self.tabsIn_tabUHPandHyper.setCurrentIndex(0)
        self.tabsIn_tabPDandHyper.setCurrentIndex(0)
        self.tabsIn_tabThreeModels.setCurrentIndex(0)
        self.tabsIn_tabUHP.currentChanged['int'].connect(self.stackedWidgetIn_pageUHP.setCurrentIndex)
        self.tabsIn_pageCP.currentChanged['int'].connect(self.stackedWidgetIn_pageCP.setCurrentIndex)
        self.tabsIn_tabPD.currentChanged['int'].connect(self.stackedWidgetIn_pagePD.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditCPSGComplexNumber1, self.lineEditCPSGComplexNumber2)
        MainWindow.setTabOrder(self.lineEditCPSGComplexNumber2, self.spinBoxCPSGCommon)
        MainWindow.setTabOrder(self.spinBoxCPSGCommon, self.toolButtonMS)
        MainWindow.setTabOrder(self.toolButtonMS, self.toolButtonArt)
        MainWindow.setTabOrder(self.toolButtonArt, self.tabsIn_pageHP)
        MainWindow.setTabOrder(self.tabsIn_pageHP, self.tabsIn_pageCP)
        MainWindow.setTabOrder(self.tabsIn_pageCP, self.tabsIn_tabUHP)
        MainWindow.setTabOrder(self.tabsIn_tabUHP, self.tabsIn_tabPD)
        MainWindow.setTabOrder(self.tabsIn_tabPD, self.tabsIn_tabHyper)
        MainWindow.setTabOrder(self.tabsIn_tabHyper, self.textWelcome)
        MainWindow.setTabOrder(self.textWelcome, self.tabsIn_tabUHPandPD)
        MainWindow.setTabOrder(self.tabsIn_tabUHPandPD, self.tabsIn_tabUHPandHyper)
        MainWindow.setTabOrder(self.tabsIn_tabUHPandHyper, self.tabsIn_tabPDandHyper)
        MainWindow.setTabOrder(self.tabsIn_tabPDandHyper, self.tabsIn_tabThreeModels)
        MainWindow.setTabOrder(self.tabsIn_tabThreeModels, self.toolButtonCP)
        MainWindow.setTabOrder(self.toolButtonCP, self.toolButtonHome)
        MainWindow.setTabOrder(self.toolButtonHome, self.pushButtonCPSGCommon)
        MainWindow.setTabOrder(self.pushButtonCPSGCommon, self.toolButtonHP)
        MainWindow.setTabOrder(self.toolButtonHP, self.toolButtonTS)
        MainWindow.setTabOrder(self.toolButtonTS, self.pushButtonCPSGApollonius)
        MainWindow.setTabOrder(self.pushButtonCPSGApollonius, self.pushButtonCPSGSteiner)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HG App"))
        self.toolButtonHome.setText(_translate("MainWindow", "Home"))
        self.toolButtonCP.setText(_translate("MainWindow", "Complex Plane"))
        self.toolButtonHP.setText(_translate("MainWindow", "Hyperbolic Plane"))
        self.toolButtonTS.setText(_translate("MainWindow", "Teichmüller Spaces"))
        self.toolButtonMS.setText(_translate("MainWindow", "Moduli Spaces"))
        self.toolButtonArt.setText(_translate("MainWindow", "Art"))
        self.textWelcome.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">Welcome to HG APP!</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">This app is designed to help you visualize properties of the Hyperbolic Plane in its three models -the upper half plane, the Poincaré disc and the hyperboloid.</span></p></body></html>"))
        self.tabsIn_pageCP.setTabText(self.tabsIn_pageCP.indexOf(self.tabCPSteinerGrids), _translate("MainWindow", "Steiner grids"))
        self.tabsIn_pageCP.setTabText(self.tabsIn_pageCP.indexOf(self.tabCPMobiusTransformations), _translate("MainWindow", "Möbius transformations"))
        self.pushButtonCPSGCommon.setText(_translate("MainWindow", "Show Common Circles"))
        self.lineEditCPSGComplexNumber2.setPlaceholderText(_translate("MainWindow", "c+dj"))
        self.lineEditCPSGComplexNumber1.setPlaceholderText(_translate("MainWindow", "a+bj"))
        self.pushButtonCPSGApollonius.setText(_translate("MainWindow", "Show Apollonius Circles"))
        self.pushButtonCPSGSteiner.setText(_translate("MainWindow", "Show Steiner Grid"))
        self.labelCPSGLoxodromes.setText(_translate("MainWindow", "Show loxodromes"))
        self.lineEditCPMTOrbitsComplexNumberalpha.setPlaceholderText(_translate("MainWindow", "\\alpha"))
        self.lineEditCPMTOrbitsComplexNumberbeta.setPlaceholderText(_translate("MainWindow", "\\beta"))
        self.lineEditCPMTOrbitsComplexNumbergamma.setPlaceholderText(_translate("MainWindow", "\\gamma"))
        self.lineEditCPMTOrbitsComplexNumberdelta.setPlaceholderText(_translate("MainWindow", "\\delta"))
        self.lineEditCPMTOrbitsComplexNumberz_0.setPlaceholderText(_translate("MainWindow", "z_0"))
        self.pushButtonCPMTOrbitsSinglePoint.setText(_translate("MainWindow", "PushButton"))
        self.pushButtonCPMTOrbitsRandomCircle.setText(_translate("MainWindow", "Show Orbit!"))
        self.pushButtonCPMTOrbitsSteinerGrid.setText(_translate("MainWindow", "Behavior on SG"))
        self.pushButtonCPClearCanvas.setText(_translate("MainWindow", "Clear Canvas"))
        self.radioButtonCPoo.setText(_translate("MainWindow", "oo"))
        self.tabsIn_tabUHP.setTabText(self.tabsIn_tabUHP.indexOf(self.tabUHPBasicConstructions), _translate("MainWindow", "Basic Constructions"))
        self.tabsIn_tabUHP.setTabText(self.tabsIn_tabUHP.indexOf(self.tabUHPGeodesicMotion), _translate("MainWindow", "Geodesic Motion"))
        self.tabsIn_tabUHP.setTabText(self.tabsIn_tabUHP.indexOf(self.tabUHPCircularMotion), _translate("MainWindow", "Circular Motion"))
        self.tabsIn_tabUHP.setTabText(self.tabsIn_tabUHP.indexOf(self.tabUHPIsometries), _translate("MainWindow", "Isometries"))
        self.radioButtonCPoo_2.setText(_translate("MainWindow", "oo"))
        self.pushButtonUHPClearCanvas.setText(_translate("MainWindow", "Clear Canvas"))
        self.labelUHPBChdistance.setText(_translate("MainWindow", "h Distance:"))
        self.pushButtonUHPBCShowGeodesicSegment.setText(_translate("MainWindow", "Show!"))
        self.labelUHPBCto.setText(_translate("MainWindow", "To:"))
        self.labelUHPBCfrom.setText(_translate("MainWindow", "From:"))
        self.lineEditUHPBCComplexNumber1.setPlaceholderText(_translate("MainWindow", "a+bj"))
        self.lineEditUHPBCComplexNumber2.setPlaceholderText(_translate("MainWindow", "c+dj"))
        self.labelUHPBChdistancenumber.setText(_translate("MainWindow", "--"))
        self.radioButtonUHPBCGeodesicSegments.setText(_translate("MainWindow", "Geodesic segments"))
        self.radioButtonUHPBCConvexHull.setText(_translate("MainWindow", "Convex hull"))
        self.pushButtonUHPGMShowGeodesic.setText(_translate("MainWindow", "Show!"))
        self.lineEditUHPGMComplexNumber1.setPlaceholderText(_translate("MainWindow", "a+bj"))
        self.lineEditUHPGMComplexNumber2.setPlaceholderText(_translate("MainWindow", "c+dj"))
        self.labelUHPGMhdistance.setText(_translate("MainWindow", "h Distance:"))
        self.labelUHPGMhdistancenumber.setText(_translate("MainWindow", "--"))
        self.labelUHPGMfrom.setText(_translate("MainWindow", "From:"))
        self.labelUHPGMto.setText(_translate("MainWindow", "To:"))
        self.radioButtonUHPGMPointPoint.setText(_translate("MainWindow", "Point to Point"))
        self.radioButtonUHPGMPointVector.setText(_translate("MainWindow", "Point Vector"))
        self.radioButtonUHPGMGeoParamByArcLength.setText(_translate("MainWindow", "Geodesics param. by arc length"))
        self.radioButtonUHPGMWaves.setText(_translate("MainWindow", "Waves"))
        self.pushButtonUHPCMCircMotionAntiClockwise.setText(_translate("MainWindow", "PushButton"))
        self.labelUHPyNumber.setText(_translate("MainWindow", "--"))
        self.labelUHPxNumber.setText(_translate("MainWindow", "--"))
        self.tabsIn_pageHP.setTabText(self.tabsIn_pageHP.indexOf(self.tabUHP), _translate("MainWindow", "Upper half plane"))
        self.tabsIn_tabPD.setTabText(self.tabsIn_tabPD.indexOf(self.tabPDBasicConstructions), _translate("MainWindow", "Basic Constructions"))
        self.tabsIn_tabPD.setTabText(self.tabsIn_tabPD.indexOf(self.tabPDGeodesicMotion), _translate("MainWindow", "Geodesic Motion"))
        self.tabsIn_tabPD.setTabText(self.tabsIn_tabPD.indexOf(self.tabPDCircularMotion), _translate("MainWindow", "Circular Motion"))
        self.tabsIn_tabPD.setTabText(self.tabsIn_tabPD.indexOf(self.tabPDIsometries), _translate("MainWindow", "Isometries"))
        self.labelPDBChdistance.setText(_translate("MainWindow", "h Distance:"))
        self.pushButtonPDBCShowGeodesicSegment.setText(_translate("MainWindow", "Show!"))
        self.labelPDBCto.setText(_translate("MainWindow", "To:"))
        self.labelPDBCfrom.setText(_translate("MainWindow", "From:"))
        self.lineEditPDBCComplexNumber1.setPlaceholderText(_translate("MainWindow", "a+bj"))
        self.lineEditPDBCComplexNumber2.setPlaceholderText(_translate("MainWindow", "c+dj"))
        self.labelPDBChdistancenumber.setText(_translate("MainWindow", "--"))
        self.pushButtonPDGMShowGeodesic.setText(_translate("MainWindow", "Show!"))
        self.lineEditPDGMComplexNumber1.setPlaceholderText(_translate("MainWindow", "a+bj"))
        self.lineEditPDGMComplexNumber2.setPlaceholderText(_translate("MainWindow", "c+dj"))
        self.labelPDGMhdistance.setText(_translate("MainWindow", "h Distance:"))
        self.labelPDGMhdistancenumber.setText(_translate("MainWindow", "--"))
        self.labelPDGMfrom.setText(_translate("MainWindow", "From:"))
        self.labelPDGMto.setText(_translate("MainWindow", "To:"))
        self.pushButtonPDCMCircMotionAntiClockwise.setText(_translate("MainWindow", "PushButton"))
        self.checkBoxPDEnableClickOnCanvas.setText(_translate("MainWindow", "Enable clicking on canvas"))
        self.labelPDyNumber.setText(_translate("MainWindow", "--"))
        self.labelPDxNumber.setText(_translate("MainWindow", "--"))
        self.labelPDNormNumber.setText(_translate("MainWindow", "--"))
        self.pushButtonPDClearCanvas.setText(_translate("MainWindow", "Clear Canvas"))
        self.tabsIn_pageHP.setTabText(self.tabsIn_pageHP.indexOf(self.tabPD), _translate("MainWindow", "Poincaré Disc"))
        self.tabsIn_tabHyper.setTabText(self.tabsIn_tabHyper.indexOf(self.tabHyperBasicConstructions), _translate("MainWindow", "Basic Constructions"))
        self.tabsIn_tabHyper.setTabText(self.tabsIn_tabHyper.indexOf(self.tabHyperGeodesicMotion), _translate("MainWindow", "Geodesic Motion"))
        self.tabsIn_tabHyper.setTabText(self.tabsIn_tabHyper.indexOf(self.tabHyperCircularMotion), _translate("MainWindow", "Circular Motion"))
        self.tabsIn_tabHyper.setTabText(self.tabsIn_tabHyper.indexOf(self.tabHyperIsometries), _translate("MainWindow", "Isometries"))
        self.tabsIn_pageHP.setTabText(self.tabsIn_pageHP.indexOf(self.tabHyper), _translate("MainWindow", "Hyperboloid"))
        self.tabsIn_tabUHPandPD.setTabText(self.tabsIn_tabUHPandPD.indexOf(self.tabUHPandPDBasicConstructions), _translate("MainWindow", "Basic Constructions"))
        self.tabsIn_tabUHPandPD.setTabText(self.tabsIn_tabUHPandPD.indexOf(self.tabUHPandPDGeodesicMotion), _translate("MainWindow", "Geodesic Motion"))
        self.tabsIn_tabUHPandPD.setTabText(self.tabsIn_tabUHPandPD.indexOf(self.tabUHPandPDCircularMotion), _translate("MainWindow", "Circular Motion"))
        self.tabsIn_tabUHPandPD.setTabText(self.tabsIn_tabUHPandPD.indexOf(self.tabUHPandPDIsometries), _translate("MainWindow", "Isometries"))
        self.tabsIn_pageHP.setTabText(self.tabsIn_pageHP.indexOf(self.tabUHPandPD), _translate("MainWindow", "UHP/PD"))
        self.tabsIn_tabUHPandHyper.setTabText(self.tabsIn_tabUHPandHyper.indexOf(self.tabUHPandHyperBasicConstructions), _translate("MainWindow", "Basic Constructions"))
        self.tabsIn_tabUHPandHyper.setTabText(self.tabsIn_tabUHPandHyper.indexOf(self.tabUHPandHyperGeodesicMotion), _translate("MainWindow", "Geodesic Motion"))
        self.tabsIn_tabUHPandHyper.setTabText(self.tabsIn_tabUHPandHyper.indexOf(self.tabUHPandHyperCircularMotion), _translate("MainWindow", "Circular Motion"))
        self.tabsIn_tabUHPandHyper.setTabText(self.tabsIn_tabUHPandHyper.indexOf(self.tabUHPandHyperIsometries), _translate("MainWindow", "Isometries"))
        self.tabsIn_pageHP.setTabText(self.tabsIn_pageHP.indexOf(self.tabUHPandHyper), _translate("MainWindow", "UHP/Hyperboloid"))
        self.tabsIn_tabPDandHyper.setTabText(self.tabsIn_tabPDandHyper.indexOf(self.tabPDandHyperBasicConstructions), _translate("MainWindow", "Basic Constructions"))
        self.tabsIn_tabPDandHyper.setTabText(self.tabsIn_tabPDandHyper.indexOf(self.tabPDandHyperGeodesicMotion), _translate("MainWindow", "Geodesic Motion"))
        self.tabsIn_tabPDandHyper.setTabText(self.tabsIn_tabPDandHyper.indexOf(self.tabPDandHyperCircularMotion), _translate("MainWindow", "Circular Motion"))
        self.tabsIn_tabPDandHyper.setTabText(self.tabsIn_tabPDandHyper.indexOf(self.tabPDandHyperIsometries), _translate("MainWindow", "Isometries"))
        self.tabsIn_pageHP.setTabText(self.tabsIn_pageHP.indexOf(self.tabPDandHyper), _translate("MainWindow", "PD/Hyperboloid"))
        self.tabsIn_tabThreeModels.setTabText(self.tabsIn_tabThreeModels.indexOf(self.tabThreeModelsBasicConstructions), _translate("MainWindow", "Basic Constructions"))
        self.tabsIn_tabThreeModels.setTabText(self.tabsIn_tabThreeModels.indexOf(self.tabThreeModelsGeodesicMotion), _translate("MainWindow", "Geodesic Motion"))
        self.tabsIn_tabThreeModels.setTabText(self.tabsIn_tabThreeModels.indexOf(self.tabThreeModelsCircularMotion), _translate("MainWindow", "Circular Motion"))
        self.tabsIn_tabThreeModels.setTabText(self.tabsIn_tabThreeModels.indexOf(self.tabThreeModelsIsometries), _translate("MainWindow", "Isometries"))
        self.tabsIn_pageHP.setTabText(self.tabsIn_pageHP.indexOf(self.tabThreeModels), _translate("MainWindow", "All three models"))

from mplwidget import MplWidget
from pyqtgraph import PlotWidget
from pyqtgraph.opengl import GLViewWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

